### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by ImJaineel** [Ekultek/WhatBreach#15]
command entered: python3 whatbreach.py

error is shown:
Traceback (most recent call last):
  File "whatbreach.py", line 1, in <module>
    from whatbreach.main import main                          
  File "/root/WhatBreach/whatbreach/main.py", line 5, in <module>
    from lib.cmd import Parser                                     
  File "/root/WhatBreach/lib/cmd.py", line 3, in <module>                 
    import lib.settings                                                   
  File "/root/WhatBreach/lib/settings.py", line 11, in <module>
    from hookers.pastebin_hook import PastebinRawHook
  File "/root/WhatBreach/hookers/pastebin_hook.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by Ekultek** [comment]
pip3 install -r requirements.txt

**Comment by ImJaineel** [comment]
Tried but still same error

**Comment by Stakingsoup** [comment]
> pip3 install -r requirements.txt

Same Bro

**Comment by selimxsuha** [comment]
run with sudo after u do this "in formatter.py change raw_input to just input"

**Comment by raushnn** [comment]
> run with sudo after u do this "in formatter.py change raw_input to just input"

tried man but still same error

**Comment by raushnn** [comment]
> pip3 install -r requirements.txt

requirement already satisfied but still giving error

**Comment by raushnn** [comment]
Again, If I'm entering command " python3 whatbreach.py -e testmail123@mail.com 

> Traceback (most recent call last):
  File "whatbreach.py", line 5, in <module>
    main()
  File "/home/raushan/WhatBreach/whatbreach/main.py", line 45, in main
    api_tokens = grab_api_tokens()
  File "/home/raushan/WhatBreach/lib/settings.py", line 248, in grab_api_tokens
    tokens[token_identifier] = json.load(data)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
![image](https://user-images.githubusercontent.com/44736489/89961196-a4e92200-dc5e-11ea-8d0d-1b8854e4500a.png)

**Comment by gr3ym1nd** [comment]
> Again, If I'm entering command " python3 whatbreach.py -e [testmail123@mail.com](mailto:testmail123@mail.com)
> 
> > Traceback (most recent call last):
> > File "whatbreach.py", line 5, in 
> > main()
> > File "/home/raushan/WhatBreach/whatbreach/main.py", line 45, in main
> > api_tokens = grab_api_tokens()
> > File "/home/raushan/WhatBreach/lib/settings.py", line 248, in grab_api_tokens
> > tokens[token_identifier] = json.load(data)
> > File "/usr/lib/python3.8/json/**init**.py", line 293, in load
> > return loads(fp.read(),
> > File "/usr/lib/python3.8/json/**init**.py", line 357, in loads
> > return _default_decoder.decode(s)
> > File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
> > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
> > raise JSONDecodeError("Expecting value", s, err.value) from None
> > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > ![image](https://user-images.githubusercontent.com/44736489/89961196-a4e92200-dc5e-11ea-8d0d-1b8854e4500a.png)

Same here.
Anyone solved this problem?

**Comment by Ekultek** [comment]
try:
```
pip3 uninstall requests
pip3 install -r requirements.txt
```

**Comment by Mgil10** [comment]
> try:
> 
> ```
> pip3 uninstall requests
> pip3 install -r requirements.txt
> ```

Don't work

**Comment by Ekultek** [comment]
@raushnn @gr3ym1nd you didn't fill out the api data. So when it's trying to load the files it's not getting them. Do `rm -rf ~/.whatbreach_home` and rerun and answer the questions with the API keys. As for the requests module being funky, @Mgil10,  check if requests is installed with `pip list` if you see it do `pip uninstall requests` and `pip install requests`. This is your computers or requests installations issue, it has nothing to do with WhatBreach.

**Comment by jakestpeter** [comment]
How do you rerun and answer the questions? I can't figure out where the API keys go ...
