### ISSUE TITLE
Is this project still maintained? :)

### ISSUE THREAD

**Issue by noire-x** [Ekultek/WhatBreach#25]
Hi there guys, was wondering if this project still maintained. Thanks!

**Comment by Ekultek** [comment]
Hi, I don't really have time to continue development so not really sorry. I would suggest h8mail if you're looking for a maintained project

**Comment by noire-x** [comment]
thanks for your reply and good luck with everything!

**Comment by Ekultek** [comment]
No problem, you as well!

**Comment by Ekultek** [comment]
Hey, I have added a new contributor @Dayhta who will be maintaining the project from now on. I will help where I can
