### ISSUE TITLE
How to fix you have been blocked from HIBP, skipping and continuing, pass the `--do-retry` flag to retry the requests on failure (max of 3 retries will be attempted)

### ISSUE THREAD

**Issue by cybert79** [Ekultek/WhatBreach#7]
When I run the command I get the message you have been blocked from HIBP, skipping and continuing, pass the `--do-retry` flag to retry the requests on failure (max of 3 retries will be attempted).

Now from this IP I have never tried to query HIBP,...

**Comment by cybert79** [comment]
PS: It seems from 18 of august the api v2 will stop, and only a paid api v3 will be available

**Comment by Ekultek** [comment]
Easiest way is to change your IP. For some reason your IP is blocked. You could also try using a random user agent. I’ll look into the API thank you

**Comment by Ekultek** [comment]
HIBP api hook has been updated
